const centerList = [
  {
    _id: "66f52b28426941001dd5297d",
    gymName: "갈산 제이폭스멀티짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1922db0964e4f2d8a2/2aGrgBwbj3CW2tnnfU9KADLywLJaAqtDFotH.list_photo.jpg",
    address: "인천 부평구 갈산동",
    location: [126.72621949831611, 37.511417193261195],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["주짓수", "복싱", "킥복싱", "무에타이"],
    program: {
      free: "",
    },
    service: {
      free: "주차 무료 서비스",
    },
    price: {
      name: "제이폭스멀티짐 회원권 (주짓수, 킥복싱, 복싱, 무에타이)",
      count: null,
      isLowestPrice: false,
      lowestPrice: 300000,
      originalPrice: 300000,
      period: 3,
      priceType: "period",
      itemTags: ["무에타이", "킥복싱", "복싱", "주짓수"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "5a16bfd5e3426a253d9ae1a1",
    gymName: "갈산 팀복싱짐 휘트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15fe8dd5b822a4e411/2WiqieFqx2qPG7iUQeT5S89RL6ZoyawaKHYH.list_photo.jpg",
    address: "인천 부평구 갈산동",
    location: [126.725725, 37.511593],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["복싱", "헬스"],
    program: {
      free: "/",
    },
    service: {
      free: "운동복 / 수건 /",
    },
    price: {
      name: "헬스",
      count: null,
      isLowestPrice: false,
      lowestPrice: 360000,
      originalPrice: 360000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.88,
      count: 2,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6478433bf3cbba001d5f4f55",
    gymName: "부평 노력의천재 헬스&PT",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18875c6a0c120fe43/kXkA9EVriGUYZArwZQn5eXDnp9mPDznf4Rbs3HXMkt.jpg",
    address: "인천 부평구 갈산동",
    location: [126.72356183533834, 37.515925019863396],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "️수건",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 400000,
      originalPrice: 400000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "629efec04600ae001d30a87b",
    gymName: "삼산 별필라테스&플라잉요가 ",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1813d131f952ea9331/4K8g5puN9cxSiyAp4tn59XEC3zj2kUCY3x1nRzn8TR9a.jpg",
    address: "인천 부평구 삼산동",
    location: [126.73246445554047, 37.51575631002796],
    isWomenOnly: true,
    isReservationRequired: true,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["필라테스", "플라잉요가"],
    program: {
      free: "",
    },
    service: {
      free: "",
    },
    price: {
      name: "그룹 필라테스+플라잉 요가 (월 10회)",
      count: 110,
      isLowestPrice: false,
      lowestPrice: 1271600,
      originalPrice: 1271600,
      period: null,
      priceType: "count",
      itemTags: ["필라테스", "플라잉요가"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 4,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "5a16becae3426a253d9ae19f",
    gymName: "갈산 인천 베스트 클라이밍",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15fe8d946e857f0b2/Small)BestClimbing.jpg",
    address: "인천 부평구 갈산동",
    location: [126.726102, 37.517559],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["클라이밍"],
    program: {
      free: "",
    },
    service: {
      free: "",
    },
    price: {
      name: "클라이밍",
      count: null,
      isLowestPrice: false,
      lowestPrice: 250000,
      originalPrice: 250000,
      period: 3,
      priceType: "period",
      itemTags: ["클라이밍"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.75,
      count: 6,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "59f61259b0993a41223b764d",
    gymName: "삼산 테크노짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15f6937ac63467f188/Small)TechnoGym.jpg",
    address: "인천 부평구 삼산동",
    location: [126.735858, 37.507097],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스"],
    program: {
      free: "-G.X [파워덤벨 / 코어트레이닝 / 요가 / 댄스에어로빅 / 전신스트레칭 / S-라인체조] / / O.T 1회 (*간단한 기구설명 및 동기부여)",
    },
    service: {
      free: "주차 3시간 / 인바디 측정",
    },
    price: {
      name: "헬스+G.X [부부관장님이 직접진행하는 티칭 그룹수업]",
      count: null,
      isLowestPrice: true,
      lowestPrice: 501000,
      originalPrice: 505000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 10,
    },
    review: {
      rate: 5,
      count: 23,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "61837da96bdf9700391007f7",
    gymName: "부평구청 타임짐휘트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce9a2dc2f2ea44fe/4K7xr2pEyhVMzEc5bz6PhzPHh3kDe3k4dKF83PPF9UTZ.jpg",
    address: "인천 부평구 부평동",
    location: [126.719892, 37.505882],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "️가변주차가능 / ️샤워시설 / ️WI-FI / ️수건 / ️인바디 검사",
    },
    price: {
      name: "헬스 이용권",
      count: null,
      isLowestPrice: true,
      lowestPrice: 359000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 6,
    },
    review: {
      rate: 5,
      count: 3,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "636b0d23d6679f001d132deb",
    gymName: "부평 PT시작",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1845a2b539e5f19578/4K8ggnJZ5AD7w3khCU7XVtjhLAGinLX5NPdxT2qVqVpU.jpg",
    address: "인천 부평구 부평동",
    location: [126.72103519839345, 37.50489982808945],
    isWomenOnly: false,
    isReservationRequired: true,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["P.T"],
    program: {
      free: "",
    },
    service: {
      free: "운동복 / 개인락커 / 커피이용",
    },
    price: {
      name: "1:1 PT",
      count: 50,
      isLowestPrice: false,
      lowestPrice: 2750000,
      originalPrice: 2750000,
      period: null,
      priceType: "count",
      itemTags: ["P.T"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62e7726ff9efad001d8e579b",
    gymName: "갈산 고바디 피트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182581702b9321a8ed/4K8gHXmjHsg3PCGKpjqdpNiBh9WZGPoGgDS1XVbPpb2x.jpg",
    address: "인천 부평구 청천동",
    location: [126.72096443314094, 37.51707444582458],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "Wi-fi / 주차장 / 수건",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 600000,
      originalPrice: 600000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.67,
      count: 3,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62a6c095123b8b001d5372bb",
    gymName: "부개 유알짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1815b6048d82eaa98f/2kbWgJMh73NPGoMP7Pc7tpU6EukEBEPzx5x7.list_photo.jpg",
    address: "인천 부평구 부개동",
    location: [126.73429263915732, 37.504191570220534],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "30회 PT 등록시! 회원복 & 락커 제공! / 수건 무료 제공 / 일일 입장제한 X / 등록시 무료 피티 1회 제공",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 7,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "66b46d2b01d0e4001dc96cc0",
    gymName: "부개 제이폭스멀티짐 ",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/19130ca71dc5b272fa/2bhfPy9XyN2BdyvQWfdx5ex1Ps9psB13ZnFL.list_photo.jpg",
    address: "인천 부평구 부개동",
    location: [126.73889210596084, 37.50358013426223],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스"],
    program: {
      free: "",
    },
    service: {
      free: "3개월 등록시 글러브, 붕대 무료증정",
    },
    price: {
      name: "제이폭스멀티짐 회원권(킥복싱,주짓구,복싱,무에타이)",
      count: null,
      isLowestPrice: false,
      lowestPrice: 300000,
      originalPrice: 300000,
      period: 3,
      priceType: "period",
      itemTags: ["복싱", "킥복싱"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6386b97eb54b10001dec4fe3",
    gymName: "부평 mgym",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184c64497a13d462cd/NV8xnm3W7Lz91cpfB6BB5qKjzHUe7Ws1PP.list_photo.jpg",
    address: "인천 부평구 부평동",
    location: [126.72965251611235, 37.49880655738467],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "O.T",
    },
    service: {
      free: "주차 (2시간)",
    },
    price: {
      name: "헬스",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "64d0d308d7c1bd001d65b785",
    gymName: "부평 키워드핏",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189cfb859c73854ec6/2WQemZ31hyjcNCtCMSpqjQvFPBsakJxSXmp3.list_photo.jpg",
    address: "인천 부평구 부평동",
    location: [126.7217453, 37.4977424],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "수건 / 락커",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 399000,
      originalPrice: 399000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "66c7ef9801d0e4001dd151e9",
    gymName: "부개 용인대 런주짓수&런킥복싱",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1917cffea84371eb27/2WQKokHScfsuvizd5Ju7G91kEn2R8y9pdyoB.list_photo.jpg",
    address: "인천 부평구 부개동",
    location: [126.73546237340084, 37.498008806885316],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["주짓수", "킥복싱"],
    program: {
      free: "",
    },
    service: {
      free: "주차 무료 서비스",
    },
    price: {
      name: "용인대 런주짓수 & 런킥복싱 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 1200000,
      originalPrice: 1200000,
      period: 12,
      priceType: "period",
      itemTags: ["주짓수", "킥복싱"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6183671e6bdf97003910046b",
    gymName: "산곡 플랜A피트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce94ad08d5c34447/4K7xr2p8vPEYxHxpJnCkzgQfgoA1CHrTYzpizPBjPa24.jpg",
    address: "인천 부평구 산곡동",
    location: [126.71299418004969, 37.50214891920522],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "탁구", "스쿼시"],
    program: {
      free: "",
    },
    service: {
      free: "주차 150분 / Wi-fi",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 10,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "61936a38e271c900398564e1",
    gymName: "부평 PT의정석 운동재활센터",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17d27d6ecb9117de10/4K7y1LZk6uGHeY8uKFvvoerx8vAzcMhZhj9HHeW8fBgt.jpg",
    address: "인천 부평구 부평동",
    location: [126.72394228220516, 37.49672824822733],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["P.T"],
    program: {
      free: "",
    },
    service: {
      free: "수건 / 락커 / Wi-fi",
    },
    price: {
      name: "1:1 P.T (횟수제)",
      count: 10,
      isLowestPrice: false,
      lowestPrice: 690000,
      originalPrice: 690000,
      period: null,
      priceType: "count",
      itemTags: ["P.T"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "60c0a19ac70b9e003995a855",
    gymName: "부개 팀타이거복싱짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179f0774361ef22f2/kXYbCnxsTYFHiFCvUChrcYKP1MrhMobhTw2sqAaWLQ.jpg",
    address: "인천 부평구 부개동",
    location: [126.73551054447834, 37.497418727855234],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["복싱"],
    program: {
      free: "G.X (20시)",
    },
    service: {
      free: "Wi-fi / 수건 / 락커",
    },
    price: {
      name: "복싱",
      count: null,
      isLowestPrice: false,
      lowestPrice: 1050000,
      originalPrice: 1050000,
      period: 12,
      priceType: "period",
      itemTags: ["복싱"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "637c6f2be38504001de06524",
    gymName: "부개 복싱인사이드짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1849e12404f415c4a3/2Y9FSvKEwfQqykN6KAP67bkUqJpE3eyEB5Jm.Small_다운로드.jpg",
    address: "인천 부평구 부개동",
    location: [126.73794680242598, 37.49738364133078],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["복싱"],
    program: {
      free: "",
    },
    service: {
      free: "",
    },
    price: {
      name: "평일기간권(주5회)",
      count: null,
      isLowestPrice: true,
      lowestPrice: 1395000,
      originalPrice: 1500000,
      period: 12,
      priceType: "period",
      itemTags: ["복싱"],
      lowestPriceRemainingCount: 10,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "65a52bbcf0f23f001d6bb16e",
    gymName: "작전 센스짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18d0d32d9a913b7ef0/2Zy5X8eGRzDzhcpEBNFcxMMv8ikM46CxqT9o.센터 Small 복사.jpg",
    address: "인천 계양구 작전동",
    location: [126.73378191160772, 37.52778313525792],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스"],
    program: {
      free: "",
    },
    service: {
      free: "️주차 2시간",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: true,
      lowestPrice: 380000,
      originalPrice: 480000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 8,
    },
    review: {
      rate: 5,
      count: 11,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "625e4ae305aa82001d4f09df",
    gymName: "작전 요가클랜",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/180405487885ee3382/4K8ftEwtVZTrTMB2wqnVGaNLD9uER67yiRDeQkoh3rsi.jpg",
    address: "인천 계양구 작전동",
    location: [126.73393334948113, 37.52814612874903],
    isWomenOnly: false,
    isReservationRequired: true,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["요가"],
    program: {
      free: "",
    },
    service: {
      free: "- 공용락커 / ※샤워시설 없습니다.",
    },
    price: {
      name: "횟수권",
      count: 100,
      isLowestPrice: false,
      lowestPrice: 1900000,
      originalPrice: 1900000,
      period: null,
      priceType: "count",
      itemTags: ["요가"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 2,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
];
