export const data = [
  {
    image:
      "https://robohash.org/exercitationemeosquas.png?size=100x100&set=set1",
    name: "Kylen Whitcher",
    color: "Maroon",
    hex_color: "#3a84dc",
    money: "$854.04",
    mobile: "Android 4.4.2",
  },
  {
    image:
      "https://robohash.org/occaecatideseruntqui.png?size=100x100&set=set1",
    name: "Judd Regardsoe",
    color: "Blue",
    hex_color: "#306a68",
    money: "$287.58",
    mobile: "Android 5.0, up to 6.0.1",
  },
  {
    image: "https://robohash.org/quienimunde.png?size=100x100&set=set1",
    name: "Alejoa Szreter",
    color: "Violet",
    hex_color: "#71a3ab",
    money: "$238.70",
    mobile: "Symbian, Series 60 UI",
  },
  {
    image: "https://robohash.org/cumsuscipitquidem.png?size=100x100&set=set1",
    name: "Algernon Cockayne",
    color: "Blue",
    hex_color: "#334348",
    money: "$331.80",
    mobile: "Microsoft Smartphone 2003",
  },
  {
    image:
      "https://robohash.org/cupiditaterepellatipsa.png?size=100x100&set=set1",
    name: "Nikolos Sabathier",
    color: "Pink",
    hex_color: "#9e80eb",
    money: "$202.34",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sedeadebitis.png?size=100x100&set=set1",
    name: "Evelina Kellet",
    color: "Teal",
    hex_color: "#049387",
    money: "$811.77",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/ininveniam.png?size=100x100&set=set1",
    name: "Bentley Crichley",
    color: "Purple",
    hex_color: "#930212",
    money: "$98.73",
    mobile: "Android 8.0, up to Android 9.0, EMUI 9.0",
  },
  {
    image:
      "https://robohash.org/doloremaliquamquaerat.png?size=100x100&set=set1",
    name: "Solomon Skinley",
    color: "Red",
    hex_color: "#edce30",
    money: "$164.51",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nonetquidem.png?size=100x100&set=set1",
    name: "Gordan Thieme",
    color: "Green",
    hex_color: "#cd2dba",
    money: "$331.89",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/porrorepellatrem.png?size=100x100&set=set1",
    name: "Val Trineman",
    color: "Teal",
    hex_color: "#e1cbe4",
    money: "$872.34",
    mobile: "Android 5.1",
  },
  {
    image:
      "https://robohash.org/voluptatemaspernaturvoluptatem.png?size=100x100&set=set1",
    name: "Nariko Swetenham",
    color: "Pink",
    hex_color: "#2b4609",
    money: "$747.26",
    mobile: "Android 4.4.2, up to 5.1",
  },
  {
    image: "https://robohash.org/nonaliquamexcepturi.png?size=100x100&set=set1",
    name: "Cordy Barrand",
    color: "Mauv",
    hex_color: "#39a3ef",
    money: "$806.99",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/velitinearum.png?size=100x100&set=set1",
    name: "Hurlee Tattersdill",
    color: "Khaki",
    hex_color: "#175570",
    money: "$102.08",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/autemrepellendusut.png?size=100x100&set=set1",
    name: "Eve Dole",
    color: "Teal",
    hex_color: "#a939da",
    money: "$227.92",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nesciuntetmolestiae.png?size=100x100&set=set1",
    name: "Sheelagh Godrich",
    color: "Aquamarine",
    hex_color: "#3b5dc1",
    money: "$373.17",
    mobile: "watchOS 6.0, up to 7.6",
  },
  {
    image: "https://robohash.org/autassumendatotam.png?size=100x100&set=set1",
    name: "Eugenius Hambers",
    color: "Maroon",
    hex_color: "#5473cb",
    money: "$746.41",
    mobile: "Android 4.3",
  },
  {
    image:
      "https://robohash.org/similiquedoloremquesed.png?size=100x100&set=set1",
    name: "Case Sands",
    color: "Orange",
    hex_color: "#990e30",
    money: "$512.53",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/estsuntqui.png?size=100x100&set=set1",
    name: "Tasia Fasler",
    color: "Yellow",
    hex_color: "#15438c",
    money: "$434.49",
    mobile: "Android 4.3, up to 4.4.2",
  },
  {
    image: "https://robohash.org/architectoabsit.png?size=100x100&set=set1",
    name: "Susanetta Thirlaway",
    color: "Goldenrod",
    hex_color: "#0e0413",
    money: "$322.06",
    mobile: "Android 4.4, up to 5.0",
  },
  {
    image:
      "https://robohash.org/quibusdamlaudantiumdolor.png?size=100x100&set=set1",
    name: "Marie-jeanne Bagnall",
    color: "Turquoise",
    hex_color: "#532854",
    money: "$448.99",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/inciduntetsoluta.png?size=100x100&set=set1",
    name: "Giles Denington",
    color: "Orange",
    hex_color: "#ddd9be",
    money: "$92.89",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/ettemporesuscipit.png?size=100x100&set=set1",
    name: "Jermaine Cockcroft",
    color: "Blue",
    hex_color: "#d339df",
    money: "$930.01",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/quotemporibusreiciendis.png?size=100x100&set=set1",
    name: "Rosalynd Akrigg",
    color: "Yellow",
    hex_color: "#b2b13e",
    money: "$515.06",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/dictafugaenim.png?size=100x100&set=set1",
    name: "Washington Stidson",
    color: "Blue",
    hex_color: "#5771dc",
    money: "$964.34",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/ametutquisquam.png?size=100x100&set=set1",
    name: "Vinni Rockcliff",
    color: "Puce",
    hex_color: "#59ac24",
    money: "$127.76",
    mobile: "Android 4.4.2, Amigo OS 2",
  },
  {
    image: "https://robohash.org/sitsimiliqueet.png?size=100x100&set=set1",
    name: "Nanci Kerfoot",
    color: "Blue",
    hex_color: "#97bfe0",
    money: "$512.81",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/sednihilsit.png?size=100x100&set=set1",
    name: "Alika Roskell",
    color: "Goldenrod",
    hex_color: "#5fd70b",
    money: "$181.76",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/noncumqueasperiores.png?size=100x100&set=set1",
    name: "Issiah Kinsella",
    color: "Crimson",
    hex_color: "#d993ba",
    money: "$931.13",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sedestillum.png?size=100x100&set=set1",
    name: "North Dorrance",
    color: "Blue",
    hex_color: "#d0cdea",
    money: "$287.40",
    mobile: "Android 10, Magic UI 2",
  },
  {
    image:
      "https://robohash.org/remvoluptatumdeleniti.png?size=100x100&set=set1",
    name: "Emelen Greet",
    color: "Teal",
    hex_color: "#6ccf62",
    money: "$781.28",
    mobile: "Android 10, ColorOS 7.1",
  },
  {
    image: "https://robohash.org/itaqueeiusbeatae.png?size=100x100&set=set1",
    name: "Issiah Haliburton",
    color: "Teal",
    hex_color: "#7bd4c1",
    money: "$525.55",
    mobile: "Android 10, TCL UI",
  },
  {
    image: "https://robohash.org/ipsumnihilunde.png?size=100x100&set=set1",
    name: "Alexandra Heinzler",
    color: "Yellow",
    hex_color: "#dd7e4e",
    money: "$869.83",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quaeratetipsum.png?size=100x100&set=set1",
    name: "Amalia Lowden",
    color: "Maroon",
    hex_color: "#a7707b",
    money: "$879.76",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/totamblanditiisenim.png?size=100x100&set=set1",
    name: "Angie Maffini",
    color: "Puce",
    hex_color: "#971b02",
    money: "$625.10",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/cumminusiusto.png?size=100x100&set=set1",
    name: "Herby Shakesbye",
    color: "Khaki",
    hex_color: "#a49312",
    money: "$421.62",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloreillummollitia.png?size=100x100&set=set1",
    name: "Yetty Glidden",
    color: "Khaki",
    hex_color: "#6c3429",
    money: "$713.37",
    mobile: "Android 4.4.4, up to 6.0",
  },
  {
    image: "https://robohash.org/estrerumnisi.png?size=100x100&set=set1",
    name: "Mozelle Scragg",
    color: "Pink",
    hex_color: "#52e86a",
    money: "$655.09",
    mobile: "Android 9.0, up to Android 10, MIUI 12",
  },
  {
    image: "https://robohash.org/quooccaecatidolorem.png?size=100x100&set=set1",
    name: "Antone Knowler",
    color: "Goldenrod",
    hex_color: "#b59ca9",
    money: "$669.70",
    mobile: "Android 6.0",
  },
  {
    image:
      "https://robohash.org/atquibusdamreprehenderit.png?size=100x100&set=set1",
    name: "Caril Pentland",
    color: "Violet",
    hex_color: "#a12d52",
    money: "$582.98",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/esttemporaquia.png?size=100x100&set=set1",
    name: "Ange Blenkin",
    color: "Violet",
    hex_color: "#a96227",
    money: "$836.38",
    mobile: "Android 9.0, XOS 5.5",
  },
  {
    image: "https://robohash.org/beataeenimunde.png?size=100x100&set=set1",
    name: "Belvia Calveley",
    color: "Aquamarine",
    hex_color: "#277fc6",
    money: "$64.97",
    mobile: "Android 6.0",
  },
  {
    image: "https://robohash.org/optioquiconsectetur.png?size=100x100&set=set1",
    name: "Georgiana Bartos",
    color: "Fuscia",
    hex_color: "#5a24c9",
    money: "$307.43",
    mobile: "Android 5.0.1, up to 6.0.1",
  },
  {
    image: "https://robohash.org/eteumsuscipit.png?size=100x100&set=set1",
    name: "Jemimah Walshe",
    color: "Green",
    hex_color: "#72de40",
    money: "$230.54",
    mobile: "Android 5.1",
  },
  {
    image:
      "https://robohash.org/repellendusmolestiaeinventore.png?size=100x100&set=set1",
    name: "Georgeanne Bultitude",
    color: "Pink",
    hex_color: "#f52ec2",
    money: "$311.38",
    mobile: "Android 9.0 Pie, up to Android 10, MIUI 12",
  },
  {
    image:
      "https://robohash.org/pariaturquaeratdolorum.png?size=100x100&set=set1",
    name: "Pris Petofi",
    color: "Pink",
    hex_color: "#05d2f3",
    money: "$342.83",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eaqueetet.png?size=100x100&set=set1",
    name: "Katharyn Greaves",
    color: "Goldenrod",
    hex_color: "#dcaba1",
    money: "$570.45",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/suntomnisquos.png?size=100x100&set=set1",
    name: "Marigold Iorillo",
    color: "Goldenrod",
    hex_color: "#0e2eb9",
    money: "$778.17",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/nesciuntomnisdebitis.png?size=100x100&set=set1",
    name: "Hirsch Brabbins",
    color: "Teal",
    hex_color: "#2275c8",
    money: "$342.06",
    mobile: "Android 4.3, ColorOS",
  },
  {
    image:
      "https://robohash.org/fugiatdoloribusexplicabo.png?size=100x100&set=set1",
    name: "Brier Klimkowski",
    color: "Khaki",
    hex_color: "#ba5e85",
    money: "$74.68",
    mobile: "Android 5.1.1",
  },
  {
    image: "https://robohash.org/veltemporevelit.png?size=100x100&set=set1",
    name: "Klement Kerr",
    color: "Puce",
    hex_color: "#dd1bfc",
    money: "$245.22",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/accusamusconsequaturaliquid.png?size=100x100&set=set1",
    name: "Brandtr MacLeod",
    color: "Mauv",
    hex_color: "#f07111",
    money: "$433.60",
    mobile: "Android 8.1 Oreo",
  },
  {
    image: "https://robohash.org/atqueestnatus.png?size=100x100&set=set1",
    name: "Edee Smallcomb",
    color: "Violet",
    hex_color: "#47159a",
    money: "$332.67",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/reiciendisautemdignissimos.png?size=100x100&set=set1",
    name: "Vally Rubertis",
    color: "Red",
    hex_color: "#5f10b8",
    money: "$312.56",
    mobile: "Tizen OS 4.0",
  },
  {
    image: "https://robohash.org/utautrepudiandae.png?size=100x100&set=set1",
    name: "Willdon Rohlfing",
    color: "Indigo",
    hex_color: "#1af783",
    money: "$380.25",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/inciduntvoluptatemvel.png?size=100x100&set=set1",
    name: "Ophelia Dymoke",
    color: "Mauv",
    hex_color: "#ef5478",
    money: "$657.58",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/quiaaperiamvoluptas.png?size=100x100&set=set1",
    name: "Ezequiel Weafer",
    color: "Khaki",
    hex_color: "#6993b1",
    money: "$903.40",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/eaetvero.png?size=100x100&set=set1",
    name: "Roana Meriguet",
    color: "Fuscia",
    hex_color: "#785438",
    money: "$628.67",
    mobile: "Android 4.4.2, Funtouch 2",
  },
  {
    image:
      "https://robohash.org/consequunturitaqueanimi.png?size=100x100&set=set1",
    name: "Gare Fawlo",
    color: "Teal",
    hex_color: "#38d987",
    money: "$503.83",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/accusamusmagnampariatur.png?size=100x100&set=set1",
    name: "Anabel MacArthur",
    color: "Yellow",
    hex_color: "#1d93b2",
    money: "$32.81",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quasidignissimoscum.png?size=100x100&set=set1",
    name: "Tiphany Lenihan",
    color: "Teal",
    hex_color: "#ea6265",
    money: "$552.20",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloreautautem.png?size=100x100&set=set1",
    name: "Sonny Kordovani",
    color: "Green",
    hex_color: "#f53ea7",
    money: "$187.35",
    mobile: "Android 4.0, up to 4.2.1",
  },
  {
    image:
      "https://robohash.org/etquibusdamreprehenderit.png?size=100x100&set=set1",
    name: "Wash McGill",
    color: "Crimson",
    hex_color: "#f39a8c",
    money: "$459.52",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quieumneque.png?size=100x100&set=set1",
    name: "Natka Lindmark",
    color: "Fuscia",
    hex_color: "#a99c3b",
    money: "$339.35",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quoducimusaut.png?size=100x100&set=set1",
    name: "Sapphira Olexa",
    color: "Purple",
    hex_color: "#b60515",
    money: "$930.85",
    mobile: "Android 8.1 Oreo",
  },
  {
    image: "https://robohash.org/doloresestsit.png?size=100x100&set=set1",
    name: "Devland Skillen",
    color: "Maroon",
    hex_color: "#cdb2c7",
    money: "$307.64",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/quisquamsapienteut.png?size=100x100&set=set1",
    name: "Nanette Janz",
    color: "Yellow",
    hex_color: "#5bb5da",
    money: "$184.51",
    mobile: "Android 9.0, Funtouch 9.0",
  },
  {
    image: "https://robohash.org/veroquiased.png?size=100x100&set=set1",
    name: "Gav McFetridge",
    color: "Teal",
    hex_color: "#786663",
    money: "$912.55",
    mobile: "Symbian, Series 60 UI",
  },
  {
    image:
      "https://robohash.org/occaecatireiciendismagnam.png?size=100x100&set=set1",
    name: "Penrod Mulhill",
    color: "Red",
    hex_color: "#5c03bd",
    money: "$949.47",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/perspiciatisexercitationemaut.png?size=100x100&set=set1",
    name: "Anastasia Purselow",
    color: "Violet",
    hex_color: "#9637bb",
    money: "$239.75",
    mobile: "Microsoft Windows Phone 8.1",
  },
  {
    image:
      "https://robohash.org/rationenullaexcepturi.png?size=100x100&set=set1",
    name: "Karie McEnteggart",
    color: "Fuscia",
    hex_color: "#fc43b3",
    money: "$333.00",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/liberoquaeassumenda.png?size=100x100&set=set1",
    name: "Thalia Doodney",
    color: "Goldenrod",
    hex_color: "#bdf6d3",
    money: "$672.99",
    mobile: "Android 6.0.1, up to Android 8.0",
  },
  {
    image: "https://robohash.org/autemassumendaculpa.png?size=100x100&set=set1",
    name: "Kriste Freyne",
    color: "Aquamarine",
    hex_color: "#fd11bd",
    money: "$229.96",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/providentesseeveniet.png?size=100x100&set=set1",
    name: "Mandie Mosdell",
    color: "Pink",
    hex_color: "#2bfd8b",
    money: "$825.19",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/eumreiciendisquo.png?size=100x100&set=set1",
    name: "Merry MacDowal",
    color: "Turquoise",
    hex_color: "#f97999",
    money: "$101.54",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/rerumetexcepturi.png?size=100x100&set=set1",
    name: "Wilton Hall-Gough",
    color: "Fuscia",
    hex_color: "#5bdb84",
    money: "$165.27",
    mobile: "Microsoft Windows Mobile 6.5 Professional",
  },
  {
    image: "https://robohash.org/etmodiomnis.png?size=100x100&set=set1",
    name: "Cathie Navarre",
    color: "Pink",
    hex_color: "#19fc82",
    money: "$202.59",
    mobile: "Android 8.1 Oreo",
  },
  {
    image:
      "https://robohash.org/pariaturdoloribusvoluptas.png?size=100x100&set=set1",
    name: "Max Fechnie",
    color: "Aquamarine",
    hex_color: "#c8affc",
    money: "$629.98",
    mobile: "Symbian, S60 rel. 3.2",
  },
  {
    image: "https://robohash.org/utquilibero.png?size=100x100&set=set1",
    name: "Rowen MacKenney",
    color: "Mauv",
    hex_color: "#629913",
    money: "$898.96",
    mobile: "Android 2.2, up to 2.3, TouchWiz UI 3",
  },
  {
    image: "https://robohash.org/adipisciporroalias.png?size=100x100&set=set1",
    name: "Dare Bellelli",
    color: "Maroon",
    hex_color: "#8f74ee",
    money: "$673.90",
    mobile: "Android 2.2",
  },
  {
    image:
      "https://robohash.org/dolorumpossimusofficia.png?size=100x100&set=set1",
    name: "Lulu Hembrow",
    color: "Turquoise",
    hex_color: "#9e351b",
    money: "$174.30",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/utdistinctioaut.png?size=100x100&set=set1",
    name: "Horatio Hugues",
    color: "Green",
    hex_color: "#b5ff11",
    money: "$878.17",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/saepesednobis.png?size=100x100&set=set1",
    name: "Pierce Moring",
    color: "Aquamarine",
    hex_color: "#b5f84c",
    money: "$319.86",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quiiureveniam.png?size=100x100&set=set1",
    name: "Nevsa Antonias",
    color: "Goldenrod",
    hex_color: "#df695e",
    money: "$856.44",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/totamnonodio.png?size=100x100&set=set1",
    name: "Fidelio Hamfleet",
    color: "Blue",
    hex_color: "#a72f66",
    money: "$467.12",
    mobile: "Android 9.0, up to Android 10, MIUI 12",
  },
  {
    image: "https://robohash.org/aliquametet.png?size=100x100&set=set1",
    name: "Chaim Barbie",
    color: "Purple",
    hex_color: "#31aec6",
    money: "$210.84",
    mobile: "Symbian^3, up to Nokia Belle OS",
  },
  {
    image: "https://robohash.org/minimadoloressed.png?size=100x100&set=set1",
    name: "Germain Cobbledick",
    color: "Mauv",
    hex_color: "#5e49f0",
    money: "$528.32",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    image: "https://robohash.org/temporaeumvel.png?size=100x100&set=set1",
    name: "Sid Elby",
    color: "Turquoise",
    hex_color: "#f9d215",
    money: "$656.40",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/temporibusetneque.png?size=100x100&set=set1",
    name: "Willi Rousell",
    color: "Fuscia",
    hex_color: "#f560b9",
    money: "$444.71",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/ametestnulla.png?size=100x100&set=set1",
    name: "Vivyanne Spratt",
    color: "Blue",
    hex_color: "#f4e20b",
    money: "$188.22",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/autetnon.png?size=100x100&set=set1",
    name: "Grenville Mawd",
    color: "Purple",
    hex_color: "#f08e44",
    money: "$620.91",
    mobile: "Android 4.4.4",
  },
  {
    image:
      "https://robohash.org/suscipitdoloremquedolor.png?size=100x100&set=set1",
    name: "Bernardine Alliot",
    color: "Yellow",
    hex_color: "#8dc006",
    money: "$539.57",
    mobile: "Microsoft Windows Mobile 6.1 Professional",
  },
  {
    image: "https://robohash.org/quossitlabore.png?size=100x100&set=set1",
    name: "Leoline Okenden",
    color: "Red",
    hex_color: "#177b4e",
    money: "$33.19",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/veroautdoloremque.png?size=100x100&set=set1",
    name: "Dorry Spleving",
    color: "Yellow",
    hex_color: "#0fc6ec",
    money: "$575.92",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/debitisvelpariatur.png?size=100x100&set=set1",
    name: "Amanda Hatje",
    color: "Green",
    hex_color: "#b21caf",
    money: "$219.02",
    mobile: "Android 4.2.2, up to 4.4.2, EMUI 1.6",
  },
  {
    image:
      "https://robohash.org/maioresrepellendusblanditiis.png?size=100x100&set=set1",
    name: "Cordy Simic",
    color: "Khaki",
    hex_color: "#20af2d",
    money: "$18.37",
    mobile: "Android 9.0, EMUI 9.1",
  },
  {
    image: "https://robohash.org/eiuseligendihic.png?size=100x100&set=set1",
    name: "Carrol Lakin",
    color: "Crimson",
    hex_color: "#585a4d",
    money: "$90.94",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/natusconsequaturat.png?size=100x100&set=set1",
    name: "Bard McAviy",
    color: "Goldenrod",
    hex_color: "#e8ecaa",
    money: "$381.96",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/maioresfacilisofficiis.png?size=100x100&set=set1",
    name: "Gay Hedgeman",
    color: "Fuscia",
    hex_color: "#8b1196",
    money: "$686.23",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/consecteturodiovel.png?size=100x100&set=set1",
    name: "Jere Lethieulier",
    color: "Green",
    hex_color: "#f68a19",
    money: "$326.74",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/perspiciatismagnisit.png?size=100x100&set=set1",
    name: "Babb Richardeau",
    color: "Indigo",
    hex_color: "#003c74",
    money: "$472.07",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quoquosblanditiis.png?size=100x100&set=set1",
    name: "Gun Bradly",
    color: "Mauv",
    hex_color: "#6a58d6",
    money: "$844.47",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/quisaeperatione.png?size=100x100&set=set1",
    name: "Tucker Harraway",
    color: "Crimson",
    hex_color: "#589ae0",
    money: "$700.26",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quovoluptassequi.png?size=100x100&set=set1",
    name: "Cecilius Casassa",
    color: "Yellow",
    hex_color: "#23d17f",
    money: "$168.53",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/liberodoloremvel.png?size=100x100&set=set1",
    name: "Sashenka Purdey",
    color: "Yellow",
    hex_color: "#f84654",
    money: "$35.82",
    mobile: "Android 4.2.2",
  },
  {
    image: "https://robohash.org/doloreminsed.png?size=100x100&set=set1",
    name: "Edyth Goodinson",
    color: "Crimson",
    hex_color: "#7cb04a",
    money: "$684.07",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/voluptatemrepudiandaeut.png?size=100x100&set=set1",
    name: "Bobbie Laboune",
    color: "Pink",
    hex_color: "#8665e3",
    money: "$608.74",
    mobile: "Android 6.0, up to Android 7.0",
  },
  {
    image: "https://robohash.org/itaquequammolestiae.png?size=100x100&set=set1",
    name: "Kerwinn Paquet",
    color: "Puce",
    hex_color: "#3f22b1",
    money: "$441.69",
    mobile: "Android 5.1",
  },
  {
    image:
      "https://robohash.org/molestiasvoluptaseligendi.png?size=100x100&set=set1",
    name: "Goldi Sterry",
    color: "Green",
    hex_color: "#f912d3",
    money: "$122.74",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/suscipitesseillo.png?size=100x100&set=set1",
    name: "Lavena McKall",
    color: "Purple",
    hex_color: "#b7795a",
    money: "$385.54",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/velitrerumipsa.png?size=100x100&set=set1",
    name: "Betteann Rains",
    color: "Fuscia",
    hex_color: "#a4622d",
    money: "$4.82",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nostrumquimaxime.png?size=100x100&set=set1",
    name: "Daren Goodyer",
    color: "Crimson",
    hex_color: "#9ae5a8",
    money: "$187.48",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/rerumtemporaquia.png?size=100x100&set=set1",
    name: "Christin Mattisssen",
    color: "Khaki",
    hex_color: "#283cb0",
    money: "$435.62",
    mobile: "Android 8.1",
  },
  {
    image:
      "https://robohash.org/quaeratsaepeofficiis.png?size=100x100&set=set1",
    name: "Ignacio Barrasse",
    color: "Maroon",
    hex_color: "#7a1079",
    money: "$69.63",
    mobile: "Android 4.2",
  },
  {
    image:
      "https://robohash.org/accusantiumdelectusdebitis.png?size=100x100&set=set1",
    name: "Blake Hallam",
    color: "Orange",
    hex_color: "#c99d4d",
    money: "$426.51",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/autestlaboriosam.png?size=100x100&set=set1",
    name: "Allianora Gheorghie",
    color: "Orange",
    hex_color: "#abf60d",
    money: "$93.83",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/estcorruptiaut.png?size=100x100&set=set1",
    name: "Ariana Lumsdale",
    color: "Goldenrod",
    hex_color: "#90c2fc",
    money: "$351.55",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/doloreinoptio.png?size=100x100&set=set1",
    name: "Ravid Legrand",
    color: "Teal",
    hex_color: "#69f44c",
    money: "$795.08",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/nonquiaqui.png?size=100x100&set=set1",
    name: "Roselia Faulkener",
    color: "Turquoise",
    hex_color: "#706368",
    money: "$18.91",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/ipsasedut.png?size=100x100&set=set1",
    name: "Herb Deegin",
    color: "Blue",
    hex_color: "#b1bbb6",
    money: "$403.29",
    mobile: "Android 2.1, up to 2.2",
  },
  {
    image: "https://robohash.org/laboriosamestaut.png?size=100x100&set=set1",
    name: "Ronni Ferronet",
    color: "Blue",
    hex_color: "#70cd52",
    money: "$202.60",
    mobile: "Android 8.1",
  },
  {
    image: "https://robohash.org/velitvoluptatemut.png?size=100x100&set=set1",
    name: "Morley Reiner",
    color: "Maroon",
    hex_color: "#28a809",
    money: "$304.56",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/rationerepellendusamet.png?size=100x100&set=set1",
    name: "Bobbye Zuker",
    color: "Puce",
    hex_color: "#8295d7",
    money: "$107.30",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/suntinerror.png?size=100x100&set=set1",
    name: "Kimberley Erasmus",
    color: "Maroon",
    hex_color: "#e3b2bc",
    money: "$968.53",
    mobile: "Android 6.0",
  },
  {
    image:
      "https://robohash.org/magnamconsequaturminima.png?size=100x100&set=set1",
    name: "Della Bagnold",
    color: "Indigo",
    hex_color: "#2f7c70",
    money: "$938.75",
    mobile: "Android 4.4.2",
  },
  {
    image: "https://robohash.org/fugitoccaecatiquia.png?size=100x100&set=set1",
    name: "Tove Bavage",
    color: "Purple",
    hex_color: "#3793d9",
    money: "$524.55",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/delectusquasiet.png?size=100x100&set=set1",
    name: "Ginnie Norville",
    color: "Teal",
    hex_color: "#12a30e",
    money: "$751.15",
    mobile: "Android 4.3",
  },
  {
    image: "https://robohash.org/auttemporibusiure.png?size=100x100&set=set1",
    name: "Andy Pendergrast",
    color: "Orange",
    hex_color: "#323d6f",
    money: "$989.60",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/totamquoquia.png?size=100x100&set=set1",
    name: "Godfree Toomey",
    color: "Crimson",
    hex_color: "#41d9ca",
    money: "$686.07",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quidemquisanimi.png?size=100x100&set=set1",
    name: "Lisbeth Juris",
    color: "Maroon",
    hex_color: "#283687",
    money: "$454.57",
    mobile: "Android 10, Funtouch 10.5",
  },
  {
    image:
      "https://robohash.org/sequivoluptatemconsequatur.png?size=100x100&set=set1",
    name: "Guglielma Bim",
    color: "Pink",
    hex_color: "#c308d5",
    money: "$832.18",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/voluptatibussuntprovident.png?size=100x100&set=set1",
    name: "Ban Willcock",
    color: "Goldenrod",
    hex_color: "#f37265",
    money: "$430.31",
    mobile: "Android 7.1.1, ColorOS 3.2",
  },
  {
    image:
      "https://robohash.org/asperiorespraesentiumvoluptates.png?size=100x100&set=set1",
    name: "Marie-ann Castagneri",
    color: "Aquamarine",
    hex_color: "#21ce44",
    money: "$772.04",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/fugitquosassumenda.png?size=100x100&set=set1",
    name: "Lockwood Crufts",
    color: "Khaki",
    hex_color: "#8e682e",
    money: "$816.33",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nondoloribusin.png?size=100x100&set=set1",
    name: "Jelene Stithe",
    color: "Purple",
    hex_color: "#8e54fa",
    money: "$781.49",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/cupiditatemodivoluptatem.png?size=100x100&set=set1",
    name: "Sarita Caddan",
    color: "Aquamarine",
    hex_color: "#027d80",
    money: "$535.62",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/omniscumqueexpedita.png?size=100x100&set=set1",
    name: "Heindrick Greenland",
    color: "Orange",
    hex_color: "#555862",
    money: "$266.41",
    mobile: "Android 5.0.2",
  },
  {
    image: "https://robohash.org/autautvel.png?size=100x100&set=set1",
    name: "Roxana Coombs",
    color: "Maroon",
    hex_color: "#758ded",
    money: "$386.91",
    mobile: "Android 10, Realme UI",
  },
  {
    image: "https://robohash.org/veniamexcumque.png?size=100x100&set=set1",
    name: "Rees Padson",
    color: "Goldenrod",
    hex_color: "#7e653e",
    money: "$403.06",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/etdolorumiure.png?size=100x100&set=set1",
    name: "Nerta Schurcke",
    color: "Crimson",
    hex_color: "#f40a29",
    money: "$646.85",
    mobile: "Android 8.1, ColorOS 5.2",
  },
  {
    image: "https://robohash.org/impeditnamassumenda.png?size=100x100&set=set1",
    name: "Rhianna Pharo",
    color: "Yellow",
    hex_color: "#691b54",
    money: "$128.88",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quinihiltenetur.png?size=100x100&set=set1",
    name: "Broddie Corn",
    color: "Orange",
    hex_color: "#d3fdf9",
    money: "$17.51",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/nequererumvitae.png?size=100x100&set=set1",
    name: "Kitti Tunney",
    color: "Khaki",
    hex_color: "#a56ce8",
    money: "$390.72",
    mobile: "Android 5.0",
  },
  {
    image: "https://robohash.org/porroautin.png?size=100x100&set=set1",
    name: "Loralie Shankland",
    color: "Violet",
    hex_color: "#d577e3",
    money: "$845.87",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/officiiseaquevelit.png?size=100x100&set=set1",
    name: "Vania Sommerland",
    color: "Blue",
    hex_color: "#5b38ef",
    money: "$655.28",
    mobile: "Android 4.4.2, up to 5.1.1, TouchWiz UI",
  },
  {
    image: "https://robohash.org/nostrumdoloreautem.png?size=100x100&set=set1",
    name: "Christie Entwistle",
    color: "Blue",
    hex_color: "#beed54",
    money: "$773.17",
    mobile: "Android 2.2, up to 2.3",
  },
  {
    image: "https://robohash.org/ipsaametlaborum.png?size=100x100&set=set1",
    name: "Vaughan Flowerden",
    color: "Violet",
    hex_color: "#97fc0b",
    money: "$655.51",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/dignissimosdistinctioipsa.png?size=100x100&set=set1",
    name: "Clement Lawrence",
    color: "Fuscia",
    hex_color: "#300881",
    money: "$318.09",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sequiutet.png?size=100x100&set=set1",
    name: "Fabio Trowsdale",
    color: "Purple",
    hex_color: "#2e9858",
    money: "$902.88",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/molestiaedistinctioaut.png?size=100x100&set=set1",
    name: "Katy Skitterel",
    color: "Blue",
    hex_color: "#52445d",
    money: "$964.24",
    mobile: "Android 7.0",
  },
  {
    image: "https://robohash.org/quoettempora.png?size=100x100&set=set1",
    name: "Darnell Knowlson",
    color: "Maroon",
    hex_color: "#58d310",
    money: "$579.53",
    mobile: "Android Wear OS",
  },
  {
    image:
      "https://robohash.org/dignissimosminusipsa.png?size=100x100&set=set1",
    name: "Cos Polk",
    color: "Maroon",
    hex_color: "#178fb6",
    money: "$875.42",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/etdoloremquefugiat.png?size=100x100&set=set1",
    name: "Caryl Goadby",
    color: "Teal",
    hex_color: "#1e5791",
    money: "$531.72",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/etrerumamet.png?size=100x100&set=set1",
    name: "Artie Timson",
    color: "Purple",
    hex_color: "#7b72f3",
    money: "$17.52",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/enimpariaturmodi.png?size=100x100&set=set1",
    name: "Rolf Posnette",
    color: "Goldenrod",
    hex_color: "#79cd10",
    money: "$625.88",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/voluptatemnemoenim.png?size=100x100&set=set1",
    name: "Ivar Battersby",
    color: "Fuscia",
    hex_color: "#c4da7c",
    money: "$248.02",
    mobile: "Android 8.1 Oreo, EMUI 8",
  },
  {
    image: "https://robohash.org/blanditiisdoloreut.png?size=100x100&set=set1",
    name: "Sibby Orchard",
    color: "Yellow",
    hex_color: "#ed1550",
    money: "$743.62",
    mobile: "BlackBerry OS 7.0",
  },
  {
    image: "https://robohash.org/atomnisdignissimos.png?size=100x100&set=set1",
    name: "Mariska Dedmam",
    color: "Turquoise",
    hex_color: "#5172b1",
    money: "$402.71",
    mobile: "Android 4.0",
  },
  {
    image: "https://robohash.org/ipsumaliquidfacere.png?size=100x100&set=set1",
    name: "Johan Bertwistle",
    color: "Pink",
    hex_color: "#48adf7",
    money: "$678.21",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/perferendiseiusaliquid.png?size=100x100&set=set1",
    name: "Ramsay Crowthe",
    color: "Fuscia",
    hex_color: "#03ee09",
    money: "$930.59",
    mobile: "Android 11, OriginOS 1.0",
  },
  {
    image: "https://robohash.org/optiononofficiis.png?size=100x100&set=set1",
    name: "Giovanni Pally",
    color: "Red",
    hex_color: "#a8f294",
    money: "$407.71",
    mobile: "Android 6.0.1, up to 7.0",
  },
  {
    image:
      "https://robohash.org/perspiciatisminimaducimus.png?size=100x100&set=set1",
    name: "Cletus Andrieux",
    color: "Orange",
    hex_color: "#80d208",
    money: "$156.34",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/modimaximequi.png?size=100x100&set=set1",
    name: "Renaud Stalley",
    color: "Puce",
    hex_color: "#535d64",
    money: "$598.68",
    mobile: "Android 2.2",
  },
  {
    image: "https://robohash.org/errorlaborumdicta.png?size=100x100&set=set1",
    name: "Westleigh Escoffier",
    color: "Pink",
    hex_color: "#c43cdd",
    money: "$998.71",
    mobile: "iOS 4, up to iOS 5.1.1",
  },
  {
    image:
      "https://robohash.org/repellatliberomaiores.png?size=100x100&set=set1",
    name: "Viola Yeiles",
    color: "Blue",
    hex_color: "#3300a1",
    money: "$781.15",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/velquovelit.png?size=100x100&set=set1",
    name: "Cobbie Eckford",
    color: "Yellow",
    hex_color: "#64ba8d",
    money: "$661.20",
    mobile: "Android 5.0, Funtouch 2.1",
  },
  {
    image: "https://robohash.org/doloremnonsed.png?size=100x100&set=set1",
    name: "Pate Perryman",
    color: "Yellow",
    hex_color: "#7ef5ca",
    money: "$376.67",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/minimaveliusto.png?size=100x100&set=set1",
    name: "Estell Djekovic",
    color: "Blue",
    hex_color: "#d168d3",
    money: "$405.68",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/asperioresnihiltenetur.png?size=100x100&set=set1",
    name: "Tobias Percival",
    color: "Yellow",
    hex_color: "#55b594",
    money: "$663.33",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/consequatureumeum.png?size=100x100&set=set1",
    name: "Claire Acott",
    color: "Blue",
    hex_color: "#642964",
    money: "$248.77",
    mobile: "Android 4.1",
  },
  {
    image: "https://robohash.org/dolornobiseum.png?size=100x100&set=set1",
    name: "Mellicent Haywood",
    color: "Orange",
    hex_color: "#f33f94",
    money: "$757.20",
    mobile: "Android 4.4",
  },
  {
    image: "https://robohash.org/praesentiumremsint.png?size=100x100&set=set1",
    name: "Elinor Rosso",
    color: "Goldenrod",
    hex_color: "#720212",
    money: "$538.74",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/itaqueharummaxime.png?size=100x100&set=set1",
    name: "Ellen Village",
    color: "Pink",
    hex_color: "#8d461d",
    money: "$726.42",
    mobile: "Android 1.6",
  },
  {
    image:
      "https://robohash.org/voluptatemestveritatis.png?size=100x100&set=set1",
    name: "Sergio Pannaman",
    color: "Khaki",
    hex_color: "#0b21e7",
    money: "$366.23",
    mobile: "Android 2.3",
  },
  {
    image:
      "https://robohash.org/odiotemporibussapiente.png?size=100x100&set=set1",
    name: "Les Steuhlmeyer",
    color: "Puce",
    hex_color: "#b42f0d",
    money: "$278.48",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/recusandaequinam.png?size=100x100&set=set1",
    name: "Luigi Belt",
    color: "Khaki",
    hex_color: "#20836c",
    money: "$460.77",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/sitquisaepe.png?size=100x100&set=set1",
    name: "Gwynne Keningham",
    color: "Khaki",
    hex_color: "#886bef",
    money: "$916.34",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/verotemporaat.png?size=100x100&set=set1",
    name: "Kata Remirez",
    color: "Maroon",
    hex_color: "#9ac8a1",
    money: "$750.56",
    mobile: "Proprietary OS",
  },
  {
    image: "https://robohash.org/quosautet.png?size=100x100&set=set1",
    name: "Blondell Moxsom",
    color: "Blue",
    hex_color: "#80081c",
    money: "$509.30",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/underemillo.png?size=100x100&set=set1",
    name: "Gilberta Tieraney",
    color: "Violet",
    hex_color: "#a8c66c",
    money: "$424.99",
    mobile: "Android 7.0, ZUI 2.5",
  },
  {
    image: "https://robohash.org/eteumanimi.png?size=100x100&set=set1",
    name: "Benn Cayzer",
    color: "Khaki",
    hex_color: "#0dcf40",
    money: "$63.68",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/eosvoluptasvoluptatum.png?size=100x100&set=set1",
    name: "Elie Hakonsen",
    color: "Indigo",
    hex_color: "#020931",
    money: "$967.42",
    mobile: "Android 10",
  },
  {
    image:
      "https://robohash.org/doloresquiconsectetur.png?size=100x100&set=set1",
    name: "Nefen Gover",
    color: "Pink",
    hex_color: "#795f3c",
    money: "$694.38",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/quivoluptatemdicta.png?size=100x100&set=set1",
    name: "Francyne Mateos",
    color: "Turquoise",
    hex_color: "#814427",
    money: "$933.09",
    mobile: "Android 2.3.3, up to 4.0",
  },
  {
    image: "https://robohash.org/autnondolores.png?size=100x100&set=set1",
    name: "Sigfrid Cockshott",
    color: "Green",
    hex_color: "#bfb2d7",
    money: "$942.24",
    mobile: "Android 9.0",
  },
  {
    image: "https://robohash.org/teneturipsumiste.png?size=100x100&set=set1",
    name: "Alexa Benoit",
    color: "Red",
    hex_color: "#a9b245",
    money: "$727.79",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/etcumqueconsequatur.png?size=100x100&set=set1",
    name: "Maribeth Shawe",
    color: "Indigo",
    hex_color: "#b74770",
    money: "$716.82",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/amaximequasi.png?size=100x100&set=set1",
    name: "Franciskus Dorrian",
    color: "Maroon",
    hex_color: "#1e1de5",
    money: "$379.98",
    mobile: "BlackBerry OS 10.2",
  },
  {
    image: "https://robohash.org/exercitationemidaut.png?size=100x100&set=set1",
    name: "Rustie Gookey",
    color: "Pink",
    hex_color: "#50b4c1",
    money: "$254.38",
    mobile: "Android 5.1",
  },
  {
    image: "https://robohash.org/iddoloresquidem.png?size=100x100&set=set1",
    name: "Cole Farleigh",
    color: "Fuscia",
    hex_color: "#b23403",
    money: "$299.32",
    mobile: "Android 8.0 Oreo",
  },
  {
    image: "https://robohash.org/remineligendi.png?size=100x100&set=set1",
    name: "Kissiah Jennick",
    color: "Red",
    hex_color: "#61ca0c",
    money: "$485.38",
    mobile: "Feature phone",
  },
  {
    image: "https://robohash.org/temporibuseosad.png?size=100x100&set=set1",
    name: "Gussie Mordaunt",
    color: "Green",
    hex_color: "#ff486b",
    money: "$764.95",
    mobile: "Android 4.2",
  },
  {
    image: "https://robohash.org/saepequianostrum.png?size=100x100&set=set1",
    name: "Anastasia Bothams",
    color: "Goldenrod",
    hex_color: "#4b2962",
    money: "$895.83",
    mobile: "Android 6.0, Funtouch 2.6",
  },
  {
    image:
      "https://robohash.org/voluptatemducimusomnis.png?size=100x100&set=set1",
    name: "Patrice Vowdon",
    color: "Indigo",
    hex_color: "#44aac6",
    money: "$188.25",
    mobile: "Android 10",
  },
  {
    image:
      "https://robohash.org/debitisdoloremquevitae.png?size=100x100&set=set1",
    name: "Moreen Ladel",
    color: "Pink",
    hex_color: "#95359b",
    money: "$188.35",
    mobile: "Android-based OPhone 2.0",
  },
  {
    image:
      "https://robohash.org/minusautnecessitatibus.png?size=100x100&set=set1",
    name: "Harmonia Bunning",
    color: "Indigo",
    hex_color: "#87dec4",
    money: "$781.14",
    mobile: "Feature phone",
  },
  {
    image:
      "https://robohash.org/molestiaeducimusadipisci.png?size=100x100&set=set1",
    name: "Forester Rapp",
    color: "Khaki",
    hex_color: "#887ab0",
    money: "$86.22",
    mobile: "Android 5.1.1",
  },
  {
    image: "https://robohash.org/velvoluptaset.png?size=100x100&set=set1",
    name: "Sashenka Santacrole",
    color: "Fuscia",
    hex_color: "#0f5a97",
    money: "$68.60",
    mobile: "Android 6.0, Flyme 7.3",
  },
  {
    image: "https://robohash.org/optiorationequia.png?size=100x100&set=set1",
    name: "Christoper Swepson",
    color: "Goldenrod",
    hex_color: "#257bb9",
    money: "$780.09",
    mobile: "Android 10",
  },
  {
    image: "https://robohash.org/reiciendisnondicta.png?size=100x100&set=set1",
    name: "Lanae Morin",
    color: "Indigo",
    hex_color: "#b2da5c",
    money: "$72.34",
    mobile: "Android OS",
  },
  {
    image:
      "https://robohash.org/voluptatemexcorrupti.png?size=100x100&set=set1",
    name: "Valery Pischel",
    color: "Violet",
    hex_color: "#650105",
    money: "$547.33",
    mobile: "Android 10, MIUI 11",
  },
];
